service: udemy-aws-lambda
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: "3"

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function #インストールしたプラグイン

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-1

functions:
  first:
    handler: first.hello

  hello:
    handler: src/hello.handler

  costNotifier:
    handler: src/costNotifier.handler
    events:
      # 日本時間で毎朝9時
      - schedule: cron(0 0 * * ? *)
    environment:
      # 環境変数UDEMY_AWS_LAMBDA_SLACK_WEBHOOK_URLは、プログラムではSLACK_WEBHOOK_URLで参照するので注意
      SLACK_WEBHOOK_URL: ${ssm:UDEMY_AWS_LAMBDA_SLACK_WEBHOOK_URL}
    #      UDEMY_AWS_LAMBDA_SLACK_WEBHOOK_URL: ${ssm:UDEMY_AWS_LAMBDA_SLACK_WEBHOOK_URL}
    # Lambda関数 costNotifier の中のecメンバ関数GetCostAndUsageconst はすべてのリソース(dynamodbなど)へのアクセスを許可。プログラムで ce = new AWS.CostExplorer({ region: "us-east-1" }); としている
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ce:GetCostAndUsage
        Resource: "*"